### ISSUE TITLE
Consumer cancellation not handled

### ISSUE THREAD

**Issue by agriesser** [vert-x3/vertx-rabbitmq-client#10]
The consumer class used to consume from a queue only implements handleDelivery and none of the other callbacks. I think at least handleCancel should be implemented not necessarily by directly reregister the consumer (as this could fail due to a queue that has been deleted) but rather by notifiying the User of the Client in some way.

More Info: https://www.rabbitmq.com/consumer-cancel.html

**Comment by poiuytrez** [comment]
Fixed by Elias with #15.
