### ISSUE TITLE
Auto create of queue

### ISSUE THREAD

**Issue by mgonzaga1990** [vert-x3/vertx-rabbitmq-client#107]
Is there a way to dynamically set an auto create a queue if not exists? like passing an option?

**Comment by greatbadness** [comment]
This is already supported.

**Comment by mgonzaga1990** [comment]
@greatbadness yeah i just saw it few days ago. anyway would like to take the opportunity to ask if it has built in pooling?

**Comment by greatbadness** [comment]
I take it you mean channel pools?

**Comment by mgonzaga1990** [comment]
yes.. channel,connections..

**Comment by greatbadness** [comment]
Issue #78 is about this.

**Comment by YaytayAtWork** [comment]
Can this issue be closed?
