### ISSUE TITLE
Add TLS support 

### ISSUE THREAD

**Issue by greatbadness** [vert-x3/vertx-rabbitmq-client#108]
Introduce support for TLS

Enhance RabbitMQOptions by extending NetClientOptions.
Enable by option.setSsl(true)
Support supplying custom trust stores in formats pem, jks and p12
**jks:** options.setTrustOptions
**pem** options.setPemTrustOptions
**p12** options.PfxOptions

**Breaking changes:**
renamed options
connectionRetries  => reconnectAttempts
connectionRetryDelay => reconnectInterval

#106

**Comment by vietj** [comment]
can you list the breaking changes, i.e the options that were renamed
