### ISSUE TITLE
Cannot build on windows due to cacert bind

### ISSUE THREAD

**Issue by Yaytay** [vert-x3/vertx-rabbitmq-client#113]
### Questions

Attempting to build on Windows is giving this error:
[main] ERROR ? [rabbitmq:3.7] - Could not start container
org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException: Error parsing Bind 'C:/Users/*******/AppData/Local/Temp/.testcontainers-tmp-2417556979806674924:/etc/tls/int-ca/ca-cert-root-ca.pem:ro' (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["HostConfig"]->com.github.dockerjava.api.model.HostConfig["Binds"])
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)

### Version

master

### Context

Trying to build a clean branch.

### Steps to reproduce

1. Clone on Windows, using Docker Desktop with WSL2.
2. Attempt to build.

**Comment by vietj** [comment]
this looks weird

**Comment by vietj** [comment]
@bsideup any idea where this could come from ?

**Comment by bsideup** [comment]
@vietj may I see full stacktrace?

off-topic: any reason you didn't use the official RabbitMQ module? :) https://www.testcontainers.org/modules/rabbitmq/

**Comment by bsideup** [comment]
Oh, and btw, you're using almost 2 years old Testcontainers version:
https://github.com/vert-x3/vertx-rabbitmq-client/blob/48fd2d5938da1bb1376644cff539ec2864b55866/pom.xml#L95-L100

:D Consider using `1.15.0` (current latest)

**Comment by YaytayAtWork** [comment]
Updating testcontainers seems to fix it.
