### ISSUE TITLE
Connection recovery

### ISSUE THREAD

**Issue by Kevin-A** [vert-x3/vertx-rabbitmq-client#13]
Currently the vertx-rabbitmq-client (VRC) sets the `channel` and `connection` to `null` on receiving the `shutdownCompleted` event before attempting to reconnect. During the reconnection process consumers and publishers will not be restored.

The Java RabbitMQ client supports recovery (http://www.rabbitmq.com/api-guide.html#recovery). Is there a specific reason why this hasn't been enabled?

Activation would simply be:

```
private static Connection newConnection(JsonObject config) throws IOException, TimeoutException {
    ConnectionFactory cf = new ConnectionFactory();
    // ... other code ...
    cf.setAutomaticRecoveryEnabled(true);

    return cf.newConnection();
}
```

It seems to work, though there doesn't seem to be any logging.

**Comment by poiuytrez** [comment]
That's great. Would you be able to do a pull request with the change?
