### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by XSpazzayX** [vert-x3/vertx-rabbitmq-client#138]
I found the usage of the following code in the docs on the vertx.io website for the RabbitMQ Client in various places:
`Buffer message = Buffer.buffer("body", "Hello RabbitMQ, from Vert.x !");`

I think this should be replaced in the examples(docs) with:
`Buffer message = Buffer.buffer("Hello RabbitMQ, from Vert.x !"); `

I believe so because by looking at the Buffer.buffer(String string,String enc) method signature and the description we can see that the way the method is called currently in the docs(examples) doesn't make much sense as the first argument should be the string we are storing in the buffer, and the second argument the encoding.

**Comment by Yaytay** [comment]
Thanks, the way that the example code is built guarantees that it will compile, but not that it is actually valid.

**Comment by Yaytay** [comment]
Fixed.
