### ISSUE TITLE
Converting RabbitMQOptions to json 

### ISSUE THREAD

**Issue by XSpazzayX** [vert-x3/vertx-rabbitmq-client#139]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

Which version(s) did you encounter this bug ?
Version 4.1.4

### Context

I noticed that when calling RabbitMQOptions.toJson() on an RabbitMQOptions instance that only the fields inherited from NetClientOptions actually get converted to json.

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist
https://gist.github.com/XSpazzayX/a89936212cc3adabdf443dead2c62c6f#file-testrabbitmqoptions-java-L8

### Steps to reproduce

1. Create a RabbitMQOptions instance and call its toJson method.

### Extra

* Anything that can be relevant such as OS version, JVM version
Ubuntu 20.04, java 11

**Comment by Yaytay** [comment]
Should be fixed with #139.
