### ISSUE TITLE
RabbitMQ Client doesn't support ssl in vertx 3.9.x

### ISSUE THREAD

**Issue by bkoripalli** [vert-x3/vertx-rabbitmq-client#160]
### Questions

RabbitMQ ssl is already supported in version 4.x Can this ssl support be back ported to 3.9x

### Version

Which version(s) did you encounter this bug ?
3.9.x

**Comment by damsgaard** [comment]
Have you tried with the URL scheme for the factory?

**Comment by bkoripalli** [comment]
@damsgaard  Thank you for responding... recently migrated to vertx4 and it has ssl support through options as well. So closing the issue.
