### ISSUE TITLE
Buffering messages possible?

### ISSUE THREAD

**Issue by PatrickHuetter** [vert-x3/vertx-rabbitmq-client#23]
I would like to buffer up to x messages until the next messages will be received. 

I'm using basicConsume() to map the rabbitMQ messages to the vertx event bus but my vertx application is consuming thousands of messages which will get processed by some verticles after that. I would like to consume only a few messages from rabbitmq and process them. After a message got processed the next rabbitmq messages could be consumed (mapped to the event bus). I would like to prevent that so much messages get loaded into memory (ram) because this messages would get lost if the application stops or similar.

With the vertx-sqs plugin i could configure the buffer size but i couldn't find such configuration possibility with the vertx-rabbit-client plugin. How would you configure a buffer or build one?

**Comment by poiuytrez** [comment]
You need to set a [QOS](https://www.rabbitmq.com/releases/rabbitmq-java-client/current-javadoc/com/rabbitmq/client/Channel.html#basicQos(int)). I would also recommend to follow [this tutorial](https://www.rabbitmq.com/tutorials/tutorial-two-java.html) to understand how QOS with prefetch count works.

You can then use the vert.x rabbitmq client to set the prefetch count:
```
rabbitMQClient = RabbitMQClient.create(vertx, config);
rabbitMQClient.start(finished -> {
    rabbitMQClient.basicQos(QOS, v -> {})
}
```
