### ISSUE TITLE
How to stop/unregister basicConsume?

### ISSUE THREAD

**Issue by PatrickHuetter** [vert-x3/vertx-rabbitmq-client#24]
How can i unregister a basicConsumer?

**Comment by poiuytrez** [comment]
I have just checked. It is not implemented in the vert.x wrapper. However, it is possible in the underlying client: 
`channel.basicCancel(consumerTag);
`
Feel free to submit a pull request with an implementation. 
If you are consuming from only one queue, closing the connection might be a workaround.

**Comment by vietj** [comment]
@PatrickHuetter should we close this issue ? or keep it as place holder ?

**Comment by PatrickHuetter** [comment]
In my case it can be closed.
