### ISSUE TITLE
channel.queueBind(..,..,..,Map<S,O>) missing, needed for use of 'headers' exchange

### ISSUE THREAD

**Issue by Robin479** [vert-x3/vertx-rabbitmq-client#28]
In order to properly use a `headers` exchange, you need to pass a proper configuration during queue binding. This is currently not possible, since the `RabbitMQClient` wrapper doesn't delegate to `com.rabbitmq.client.Channel.queueBind(String, String, String, Map<String, Object>)`.

It should be fairly simple to implement, since this method is only an overload to `com.rabbitmq.client.Channel.queueBind(String, String, String)`, which the wrapper already delegates to. In fact, if you look at the upstream implementation, the later method internally calls the former one, passing `null` for the `Map<String, Object>` parameter.

Please, add this part to the `RabbitMQClientImpl` (and the matching definition to `RabbitMQClient`):
```
  @Override
  public void queueBind(String queue, String exchange, String routingKey, JsonObject arguments, Handler<AsyncResult<Void>> resultHandler) {
    forChannel(resultHandler, channel -> {
      channel.queueBind(queue, exchange, routingKey, Utils.asMap(arguments));
      return null;
    });
  }
```

**Comment by poiuytrez** [comment]
Do you have the time to submit a pull request?
