### ISSUE TITLE
queueDeclare does not accept not String configuration parameters

### ISSUE THREAD

**Issue by javiersigler** [vert-x3/vertx-rabbitmq-client#38]
Nowadays, the endpoint is defined as following:
void queueDeclare(String queue, boolean durable, boolean exclusive, boolean autoDelete, Map<String, String> config, Handler<AsyncResult<JsonObject>> resultHandler);

However, there are parameters like x-message-ttl that only accepts integers. 

I have tried to change to Map<String,Object> but I'd got an awful error 

GRAVE: io.vertx.codegen.CodeGenProcessor - Could not generate model for queueDeclare(java.lang.String,boolean,boolean,boolean,java.util.Map<java.lang.String,java.lang.Object>,io.vertx.core.Handler<io.vertx.core.AsyncResult<io.vertx.core.json.JsonObject>>): type java.util.Map<java.lang.String,java.lang.Object> is not legal for use for a parameter in code generation 
io.vertx.codegen.GenException: type java.util.Map<java.lang.String,java.lang.Object> is not legal for use for a parameter in code generation

If you are able to modify the codegen system to accept this kind of parameter, I can create a PR with this change.

**Comment by poiuytrez** [comment]
I have no idea on how to modify the codegen. @vietj could you give your input ?

**Comment by thibaultleouay** [comment]
Hey, 
According to codegen doc [1]  only the following set Param of types are permitted as parameters to any API method:
 type java.util.Map<String, C> where C contains
the set Basic
the set Json
the set Api

And Ojbect is nor Basic nor Json nor Api 


[1] https://github.com/vert-x3/vertx-codegen

**Comment by LyndonArmitage** [comment]
I've created an issue for this on the codegen project.

I am unfamiliar with the exact mechanics on how Vert.x various libraries are generated by codegen but one possible enhancement to the API may be to specify config as a `JsonObject` as it is done elsewhere in Vert.x.

That is to say; the API endpoint for adding config could look like this:

```java
  void queueDeclare(
          String queue, 
          boolean durable, 
          boolean exclusive, 
          boolean autoDelete, 
          JsonObject config, 
          Handler<AsyncResult<JsonObject>> resultHandler
  );
```

There's a method called `toArgumentsMap` that converts the current `Map<String, String>` to a `Map<String, Object>` that could then be simplified to:

```java
  private Map<String, Object> toArgumentsMap(JsonObject config) {
    return new LinkedHashMap<>(config.getMap());
  }
```

**Comment by LyndonArmitage** [comment]
FYI: Fork with what I mean: https://github.com/LyndonArmitage/vertx-rabbitmq-client (sorry I forgot to reference this issue in it).

Currently running into an issue with the codegen not being able to determine what method to use in JavaScript:

```
SEVERE: io.vertx.codegen.CodeGenProcessor - Could not generate model for io.vertx.rabbitmq.RabbitMQClient: Failed to generate because it would be impossible in target language JS at runtime to resolve which of the following overloaded methods to call in the Java API: exchangeDeclare(java.lang.String exchange, java.lang.String type, boolean durable, boolean autoDelete, java.util.Map<java.lang.String,java.lang.String> config, io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>> resultHandler) and exchangeDeclare(java.lang.String exchange, java.lang.String type, boolean durable, boolean autoDelete, io.vertx.core.json.JsonObject config, io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>> resultHandler) 
io.vertx.codegen.GenException: Failed to generate because it would be impossible in target language JS at runtime to resolve which of the following overloaded methods to call in the Java API: exchangeDeclare(java.lang.String exchange, java.lang.String type, boolean durable, boolean autoDelete, java.util.Map<java.lang.String,java.lang.String> config, io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>> resultHandler) and exchangeDeclare(java.lang.String exchange, java.lang.String type, boolean durable, boolean autoDelete, io.vertx.core.json.JsonObject config, io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>> resultHandler)
```

Are there any hints/annotations I can use to help it out? I can add an `@GenIgnore` to one of the methods and get it to build successfully but obviously we lose that method from generated code (possibly breaking the API compatibility if it's on the old one).

**Comment by LyndonArmitage** [comment]
Adding the `@GenIgnore` to the previous method works without breaking any code generated from the look of it for all but Kotlin.

If I do this and alter the example to look like this:
```java
  //pass the additional config for the exchange as map, check RabbitMQ documentation for specific config parameters
  public void exchangeDeclareWithConfig(RabbitMQClient client) {

    JsonObject config = new JsonObject();

    config.put("x-dead-letter-exchange", "my.deadletter.exchange");
    config.put("alternate-exchange", "my.alternate.exchange");
    // ...
    client.exchangeDeclare("my.exchange", "fanout", true, false, config, onResult -> {
      if (onResult.succeeded()) {
        System.out.println("Exchange successfully declared with config");
      } else {
        onResult.cause().printStackTrace();
      }
    });
  }
``` 

The resulting generated examples *do* change but they all seem to be equivalent still (correct me if I am wrong for any of these as I am not familiar with all the languages) except for, as I mentioned, Kotlin:

# Javascript

The JavaScript example is altered from:

```javascript
var config = {};

config["x-dead-letter-exchange"] = "my.deadletter.exchange";
config["alternate-exchange"] = "my.alternate.exchange";
```

to

```javascript
var config = {
};

config.x-dead-letter-exchange = "my.deadletter.exchange";
config.alternate-exchange = "my.alternate.exchange";
```

That's equivalent as far as my JavaScript knowledge goes.

# Ruby

The Ruby from:

```ruby
config = Hash.new()

config["x-dead-letter-exchange"] = "my.deadletter.exchange"
config["alternate-exchange"] = "my.alternate.exchange"
```

to

```ruby
config = {
}

config['x-dead-letter-exchange'] = "my.deadletter.exchange"
config['alternate-exchange'] = "my.alternate.exchange"
```
I assume `{}` declares a Hash the same way as `Hash.new()` and that double quotes and single quotes don't matter.

# Groovy

Groovy literally just changes the way it accesses the fields like JavaScript, from:

```groovy
config["x-dead-letter-exchange"] = "my.deadletter.exchange"
config["alternate-exchange"] = "my.alternate.exchange"
```

to

```groovy
config.x-dead-letter-exchange = "my.deadletter.exchange"
config.alternate-exchange = "my.alternate.exchange"
```

# Kotlin

Kotlin is the only one I am unsure of. Annoyingly it's initial documentation looked correct:

```kotlin
var config = mutableMapOf<String, Any?>()

config["x-dead-letter-exchange"] = "my.deadletter.exchange"
config["alternate-exchange"] = "my.alternate.exchange"
```

versus the new one:

```kotlin
var config = json {
  obj()
}

config.put("x-dead-letter-exchange", "my.deadletter.exchange")
config.put("alternate-exchange", "my.alternate.exchange")
```

Could this be an issue with the Kotlin code generation?

**Comment by chefhoobajoob** [comment]
It looks like there isn't a workaround for applications requiring non-string configuration values to be passed in to `queueDeclare` is that right?

I can't create a [priority queue](https://www.rabbitmq.com/priority.html) without specifying the max priority, for example.

If there is a workaround, what is it?

**Comment by vietj** [comment]
haven't seen this thread before because I was not subscribed to the repo notifs.

**Comment by vietj** [comment]
as @LyndonArmitage said the best is to use `JsonObject`

**Comment by vietj** [comment]
is there a branch or something I could check ?

**Comment by thibaultleouay** [comment]
@vietj  here's the pull request https://github.com/vert-x3/vertx-rabbitmq-client/pull/39
