### ISSUE TITLE
io.vertx.rabbitmq.impl.RabbitMQClientImpl#start wrong async logic

### ISSUE THREAD

**Issue by w00lf** [vert-x3/vertx-rabbitmq-client#46]
Recently i tried to use some of the Vertx async features(Future, Handlers) with RabbitMQClientImpl. However, i quickly encountered strange behavior with this method. When i map some function with `start` method of RabbitMQClientImpl there is a situation when mapping function or handler will never be called. When the client encounters `java.net.ConnectException: Connection refused`(Rabbitmq is down) it will call internally method `reconnect()` without completing or failing internal future: https://github.com/vert-x3/vertx-rabbitmq-client/blob/master/src/main/java/io/vertx/rabbitmq/impl/RabbitMQClientImpl.java#L338, as a result my application just hangs and even if the connection is restored later application cannot continue to work and need to be restarted. My question is: why cannot we pass future https://github.com/vert-x3/vertx-rabbitmq-client/blob/master/src/main/java/io/vertx/rabbitmq/impl/RabbitMQClientImpl.java#L330 to reconnect method so he will complete it after successful reconnect? I tried this code and it worked:
```
   private <T>void reconnect(Future<T> future) throws IOException {
      ....
                  try {
                    log.debug("Reconnect attempt # " + attempt);
                    connect();
                    vertx.cancelTimer(id);
                    future.complete();
                    log.info("Successfully reconnected to rabbitmq (attempt # " + attempt + ")");
```

**Comment by thibaultleouay** [comment]
Hey @w00lf 

thanks for your submission, I will take a look at it.

Thibault

**Comment by vietj** [comment]
@thibaultleouay any news about it ?

**Comment by thibaultleouay** [comment]
@vietj  sorry i had plenty of stuff to do at work i'm doing it now, 

Is there any issue of including a new dependency sniffy.junit (licence mainly)  ?

**Comment by vietj** [comment]
I'm assuming it would be a _test_ scoped dependency ?

**Comment by thibaultleouay** [comment]
Yes it is

**Comment by vietj** [comment]
that's fine then

**Comment by poiuytrez** [comment]
@thibaultleouay is currently on vacation and will be back in three weeks.
