### ISSUE TITLE
Support basicQos(int prefetchCount, boolean global)

### ISSUE THREAD

**Issue by LyndonArmitage** [vert-x3/vertx-rabbitmq-client#48]
The client seems to missing the full Qos (Consumer Prefetch) functionality described here: https://www.rabbitmq.com/consumer-prefetch.html

Specifically it is missing the functionality to set whether the Qos setting should be applied globally or not.

I propose we add a method to match the underlying RabbitMQ client's method to RabbitMQClient:

Interface:
```java
void basicQos(int prefetchCount, boolean global, Handler<AsyncResult<Void>> resultHandler);
```

Implementation:
```java
  @Override
  public void basicQos(int prefetchCount, boolean global, Handler<AsyncResult<Void>> resultHandler) {
    forChannel(resultHandler, channel -> {
      channel.basicQos(prefetchCount, global);
      return null;
    });
  }
```

**Comment by Sammers21** [comment]
@LyndonArmitage, looks great. Can you submit a PR?

**Comment by Sammers21** [comment]
@vietj, I think the issue was solved by #55

**Comment by Sammers21** [comment]
@vietj, ping, can you please close this?

**Comment by vietj** [comment]
in which version is it fixed ?
