### ISSUE TITLE
No way to get connection status

### ISSUE THREAD

**Issue by MipH** [vert-x3/vertx-rabbitmq-client#5]
vertx-rabbitmq-client doesn't use Autorecovery Connection feature of native java rabbitmq client.
And `interface RabbitMQClient` does't have method to get `connection` from `RabbitMQClientImpl`.
So there is no legal way to check `connection != null` or `connection.isOpen()` if connection to AMQP server was broken.

**Comment by poiuytrez** [comment]
Done in #6
