### ISSUE TITLE
basicConsume produces invalid message order on the eventbus channel

### ISSUE THREAD

**Issue by tibor-kocsis** [vert-x3/vertx-rabbitmq-client#51]
I created a simple test program, Sender sends a message with a counter, the Receiver receives it, but on the receiving site the order of the messages are wrong. 

https://gist.github.com/tibor-kocsis/a75d5a8cc8dd8d9a5a2f494f5bf48865

If you run the Sender, then a few minutes later the Receiver, the output will be the following:

https://pastebin.com/M2zPPe7w

As you can see, the counter is not incement at the messages that was sent before the Receiver starts. I looked into the implementation, and my guess is that the problem is in the ConsumerHandler class line 58. There is no need for the vertx.runOnContext call, you should just call the handler with the message. The handleDelivery function is called by a rabbitmq-client threadpool, and I guess vertx creates here a new context for each message, so the handler calls will run parallel, which causes the invalid order of the message delivering.

**Comment by Sammers21** [comment]
Thank you for reproducer and the issue report. I have tried and it seems that you are right about _runOnContext_. 

With changes proposed by #52, message order should be right.

**Comment by vietj** [comment]
thanks for the contribution
