### ISSUE TITLE
Consume queue as a stream

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-rabbitmq-client#53]
motivation: currently queue are consumed via the event bus with the `basicConsume` method. It does not allow for unsubscription (tag is lost), and does not work well with message acknowledgement.

changes: provide a `ReadStream` for consuming RabbitMQ queues

**Comment by Sammers21** [comment]
Now, when consuming from event bus we are forced to cast received `Object` instance to a `JsonObject` instance. Should consumption from a `ReadStream` be in that way or we should create a new class like `RabbitMQMessage`?

**Comment by vietj** [comment]
you should make a RabbitMQQueue class that extends ReadStream<Message> I think

**Comment by vietj** [comment]
or make it perhaps extends MessageConsumer like in the AMQP bridge ?

**Comment by vietj** [comment]
have a look at the AMQP brige classes

**Comment by Sammers21** [comment]
where can I find AMQP bridge classes?

**Comment by Sammers21** [comment]
if I would extend MessageConsumer, then what would be a type of message retrieved through the stream? `JsonObject`?

**Comment by vietj** [comment]
I think you just need to use readstream for now and we will see if we need something more

**Comment by Sammers21** [comment]
@vietj, just made a few changes dedicated to a new API. Awaiting your review.

**Comment by vietj** [comment]
implemented
