### ISSUE TITLE
add more docs

### ISSUE THREAD

**Issue by cazacugmihai** [vert-x3/vertx-rabbitmq-client#57]
Please document the `errorHandler` parameter:
https://github.com/vert-x3/vertx-rabbitmq-client/blob/6b55673d9c3666482a650a0fca2ab6b5d592d3e4/src/main/java/io/vertx/rabbitmq/RabbitMQClient.java#L86

Before this parameter, there is a `resultHandler` that adds some confusion.

**Comment by Sammers21** [comment]
Hi @cazacugmihai, 

Since we are going to have new API for consumption proposer here: #54, i think that the old API will be deprecated and documentation will be removed. So i m not sure that we should document it.

**Comment by cazacugmihai** [comment]
Hi, 

In this case, this issue can be closed when #54 is merged.

Thank you!

**Comment by Sammers21** [comment]
hey @cazacugmihai , PR have just merged!

**Comment by cazacugmihai** [comment]
OK. Thank you for your work!
