### ISSUE TITLE
Figure out why testBasicGet sometimes got failed

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-rabbitmq-client#58]
Here is failed build on CI: https://api.travis-ci.org/v3/job/363797955/log.txt

**Comment by Sammers21** [comment]
It seems that the `GetResponse` is null: https://github.com/vert-x3/vertx-rabbitmq-client/blob/master/src/main/java/io/vertx/rabbitmq/impl/RabbitMQClientImpl.java#L165

**Comment by vietj** [comment]
@Sammers21 yes we should get away from json format
