### ISSUE TITLE
Stop client consumer issue

### ISSUE THREAD

**Issue by spydevil** [vert-x3/vertx-rabbitmq-client#71]
Hi,
I'm using vertx api **3.5.2**.

How I can **stop or unregister** consumer, registered with `client.basicConsume`. I think this api version(**_3.5.2_**) doesn't support yet, it will be support with new version(**_3.6.0_**) [https://vertx.io/blog/eclipse-vert-x-rabbitmq-client-gets-a-new-consumer-api/](url)

My original question:
[https://stackoverflow.com/questions/51161691/vert-x-rabbitmq-endless-loop-issue](url)

**Comment by vietj** [comment]
@Sammers21 ping

**Comment by Sammers21** [comment]
@spydevil, you are right, in **_3.5.2_** you are not allowed to stop consumption without stopping the client. In 3.6.0 you can call `RabbitMQConsumer#cancel`.

**Comment by Sammers21** [comment]
@vietj, do you think we should have API for this even if `basicConsume` going to be deprecated in 3.6.0?

**Comment by vietj** [comment]
can you provide a fix soon for 3.6.0 that we can backport to 3.5.2 ?

**Comment by Sammers21** [comment]
@vietj , sure, here is the PR: #72.
