### ISSUE TITLE
Not possible to connect to a rabbitmq cluster

### ISSUE THREAD

**Issue by agriesser** [vert-x3/vertx-rabbitmq-client#8]
When creating a connection it should be possible to specify a list of rabbitmq host:port combinations in order to connect to a random host in a set of known cluster hosts. The connection should be established like this:
connectionFactory.newConnection(new Address[]{new Addres("host1",1234)});

(Address is a class of the rabbitmq client)

**Comment by Gsantomaggio** [comment]
I'd use always the class `Address` internally.
The `JsonObject` configuration something like:
`"addresses": "192.168.1.13:5672,192.168.1.10:5672"`

for  single instance:
`"addresses": "192.168.1.13:5672"`

In this way it is possible to use the `parseAddresses` function as:

  `Address[] addresses = Address.parseAddresses("192.168.1.13:5672,192.168.1.10:5672");`

and use `return cf.newConnection(addresses);` [here](https://github.com/vert-x3/vertx-rabbitmq-client/blob/master/src/main/java/io/vertx/rabbitmq/impl/RabbitMQClientImpl.java#L388)

thoughts?

**Comment by barmic** [comment]
This ticket should be closed now ;)

**Comment by Gsantomaggio** [comment]
I think so :)
