### ISSUE TITLE
More information when invalid rabbitmq uri

### ISSUE THREAD

**Issue by binout** [vert-x3/vertx-rabbitmq-client#81]
When an error occured with rabbitmq connection, the root cause is lost :

You could add the root cause message in error message.
```
Caused by: java.lang.IllegalArgumentException: Invalid rabbitmq connection uri amqps://user:password@rabbitmqeuwdevamqps***:443/common-dev
```

https://github.com/vert-x3/vertx-rabbitmq-client/blob/f9490e766fa0ea83e852f195abfebf2cc81eff27/src/main/java/io/vertx/rabbitmq/impl/RabbitMQClientImpl.java#L57

**Comment by Yaytay** [comment]
This has been done in other changes.
